apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harvester-network-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "harvester-network-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-network-controller.name" . }}
rules:
  - apiGroups: [ "network.harvester.cattle.io" ]
    resources: [ "globalnetworks", "hostnetworks", "hostnetworks/status" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
  - apiGroups: [ "harvester.cattle.io" ]
    resources: [ "settings" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "k8s.cni.cncf.io" ]
    resources: [ "network-attachment-definitions" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "nodes", "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-network-controller.name" . }}
  labels:
  {{- include "harvester-network-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-network-controller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harvester-network-controller.name" . }}
    namespace: {{ .Release.Namespace }}