apiVersion: v2
name: kubevirt-operator
version: 0.5.0
appVersion: 1.5.0
description: KubeVirt Operator provides deployment and management of KubeVirt bundle components.
icon: https://kubevirt.io/assets/images/KubeVirt_logo_color.svg
type: application
keywords:
  - kubevirt
  - operator
home: https://github.com/kubevirt/kubevirt
sources:
  - https://github.com/kubevirt/kubevirt
