# Default values for csi-snapshotter cni
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.k8s.io/sig-storage/snapshot-controller
  tag: v8.3.0
  pullPolicy: IfNotPresent
