# This daemon set is to remove loop device
# ref: https://github.com/harvester/harvester/issues/2137
{{ if .Values.longhorn.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-loop-device-cleaner
  namespace: {{ .Values.longhorn.namespaceOverride }}
  labels:
    app: longhorn-loop-device-cleaner
spec:
  selector:
    matchLabels:
      app: longhorn-loop-device-cleaner
  template:
    metadata:
      labels:
        app: longhorn-loop-device-cleaner
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: longhorn-loop-device-cleaner
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - bash
          - -c
          - |
            while true ;
            do
                for device in /sys/block/loop* ; do
                        echo "INFO: checking loop device $device"
                        if test -f "$device/loop/backing_file"; then
                                backingFile=`cat "$device/loop/backing_file"`
                                # removing trailling spaces
                                backingFile=`echo $backingFile | sed 's/ *$//g'`
                                if [[ $backingFile == *"(deleted)" ]] ; then
                                        loopDevice="/dev/$(echo $device | cut -d"/" -f4)"
                                        echo "WARN: detected removed backing file $backingFile"
                                        echo "WARN: detaching the loop device $loopDevice"
                                        losetup -d $loopDevice
                                fi
                        else
                                echo "INFO: skipping loop device $device: backing file $device/loop/backing_file doesn't exist"
                        fi
                done
                sleepingTime=60
                echo "INFO: sleeping for ${sleepingTime}s"
                sleep $sleepingTime
            done
        image: {{ .Values.generalJob.image.repository }}:{{ .Values.generalJob.image.tag }}
        imagePullPolicy: {{ .Values.generalJob.image.imagePullPolicy }}
        securityContext:
          privileged: true
  updateStrategy:
    type: RollingUpdate
{{- end -}}
