apiVersion: v2
name: harvester
version: 1.1.0-dev
appVersion: v1.1.0-dev
description: Harvester is an open source Hyper-Converged Infrastructure(HCI) solution based on Kubernetes.
icon: https://harvester.github.io/images/logo_horizontal.svg
type: application
keywords:
  - virtualization
  - HCI
home: https://github.com/harvester/harvester
sources:
  - https://github.com/harvester/harvester
dependencies:
  - name: kubevirt-operator
    version: 0.1.0
    repository: file://dependency_charts/kubevirt-operator
    condition: kubevirt-operator.enabled
    tags:
      - kubevirt
      - operator
  - name: kubevirt
    version: 0.1.0
    repository: file://dependency_charts/kubevirt
    condition: kubevirt.enabled
    tags:
      - kubevirt
      - crd
  - name: harvester-network-controller
    version: 0.3.2
    repository: https://charts.harvesterhci.io
    condition: harvester-network-controller.enabled
  - name: harvester-node-disk-manager
    version: 0.4.11
    repository: https://charts.harvesterhci.io
    condition: harvester-node-disk-manager.enabled
  - name: csi-snapshotter
    version: 0.1.0
    repository: file://dependency_charts/csi-snapshotter
    condition: csi-snapshotter.enabled
  - name: longhorn
    version: 1.3.2
    repository: https://charts.longhorn.io
    condition: longhorn.enabled
  - name: kube-vip
    version: 0.4.2
    repository: https://kube-vip.github.io/helm-charts
  - name: kube-vip-cloud-provider
    version: 0.2.1
    repository: https://kube-vip.github.io/helm-charts
  - name: harvester-load-balancer
    version: 0.1.5
    repository: https://charts.harvesterhci.io
  - name: whereabouts
    version: 0.1.1
    repository: file://dependency_charts/whereabouts
    condition: whereabouts.enabled
  - name: harvester-node-manager
    version: 0.1.4
    repository: https://charts.harvesterhci.io
