apiVersion: v2
name: harvester
version: 0.1.0
appVersion: 0.1.x
description: Harvester is a virtual machine management add-on based on KubeVirt for Kubernetes.
type: application
keywords:
  - virtualization
  - kubevirt
home: https://github.com/rancher/harvester
sources:
  - https://github.com/rancher/harvester
maintainers:
  - name: thxCode
    email: frank@rancher.com
dependencies:
  - name: kubevirt-operator
    version: 0.1.0
    repository: file://dependency_charts/kubevirt-operator
    condition: kubevirt-operator.enabled
    tags:
      - kubevirt
      - operator
  - name: kubevirt
    version: 0.1.0
    repository: file://dependency_charts/kubevirt
    condition: kubevirt.enabled
    tags:
      - kubevirt
      - crd
  - name: cdi-operator
    version: 0.1.0
    repository: file://dependency_charts/cdi-operator
    condition: cdi-operator.enabled
    tags:
      - cdi
      - operator
  - name: cdi
    version: 0.1.0
    repository: file://dependency_charts/cdi
    condition: cdi.enabled
    tags:
      - cdi
      - crd
  - name: harvester-network-controller
    version: 0.1.0
    repository: file://dependency_charts/harvester-network-controller
    condition: harvester-network-controller.enabled
  - name: multus
    version: 0.1.0
    repository: file://dependency_charts/multus
    condition: multus.enabled
  - name: minio
    # Note: Update minio image in harvester values.yaml when this version is updated.
    version: 8.0.5
    repository: https://helm.min.io
    condition: minio.enabled
