apiVersion: v2
name: harvester
version: 0.0.0-dev
appVersion: 0.1.x
description: Rancher Harvester is an open source Hyper-Converged Infrastructure(HCI) solution based on Kubernetes.
icon: https://rancher.com/imgs/brand-guidelines/rancher-logo-cow-blue.svg
type: application
keywords:
  - virtualization
  - HCI
home: https://github.com/rancher/harvester
sources:
  - https://github.com/rancher/harvester
dependencies:
  - name: kubevirt-operator
    version: 0.1.0
    repository: file://dependency_charts/kubevirt-operator
    condition: kubevirt-operator.enabled
    tags:
      - kubevirt
      - operator
  - name: kubevirt
    version: 0.1.0
    repository: file://dependency_charts/kubevirt
    condition: kubevirt.enabled
    tags:
      - kubevirt
      - crd
  - name: cdi-operator
    version: 0.1.0
    repository: file://dependency_charts/cdi-operator
    condition: cdi-operator.enabled
    tags:
      - cdi
      - operator
  - name: cdi
    version: 0.1.0
    repository: file://dependency_charts/cdi
    condition: cdi.enabled
    tags:
      - cdi
      - crd
  - name: harvester-network-controller
    version: 0.1.0
    repository: file://dependency_charts/harvester-network-controller
    condition: harvester-network-controller.enabled
  - name: multus
    version: 0.1.0
    repository: file://dependency_charts/multus
    condition: multus.enabled
  - name: csi-snapshotter
    version: 0.1.0
    repository: file://dependency_charts/csi-snapshotter
    condition: csi-snapshotter.enabled
  - name: minio
    # Note: Update minio image in harvester values.yaml when this version is updated.
    version: 8.0.5
    repository: https://helm.min.io
    condition: minio.enabled
  - name: longhorn
    version: 1.1.0
    repository: https://charts.longhorn.io
    condition: longhorn.enabled
