apiVersion: v2
name: harvester
version: 0.0.0-dev
appVersion: 0.1.x
description: Harvester is an open source Hyper-Converged Infrastructure(HCI) solution based on Kubernetes.
icon: https://harvester.github.io/images/logo_horizontal.svg
type: application
keywords:
  - virtualization
  - HCI
home: https://github.com/harvester/harvester
sources:
  - https://github.com/harvester/harvester
dependencies:
  - name: kubevirt-operator
    version: 0.5.0
    repository: file://dependency_charts/kubevirt-operator
    condition: kubevirt-operator.enabled
    tags:
      - kubevirt
      - operator
  - name: kubevirt
    version: 0.1.0
    repository: file://dependency_charts/kubevirt
    condition: kubevirt.enabled
    tags:
      - kubevirt
      - crd
  - name: cdi
    version: 0.2.0
    repository: file://dependency_charts/cdi
    condition: cdi.enabled
    tags:
      - cdi
      - crd
  - name: harvester-network-controller
    version: 1.6.1
    repository: https://charts.harvesterhci.io
    condition: harvester-network-controller.enabled
  - name: harvester-networkfs-manager
    version: 1.6.1
    repository: https://charts.harvesterhci.io
    condition: harvester-networkfs-manager.enabled
  - name: harvester-node-disk-manager
    version: 1.6.1
    repository: https://charts.harvesterhci.io
    condition: harvester-node-disk-manager.enabled
  - name: csi-snapshotter
    version: 0.2.0
    repository: file://dependency_charts/csi-snapshotter
    condition: csi-snapshotter.enabled
  - name: longhorn
    version: 1.9.2
    repository: https://charts.longhorn.io
    condition: longhorn.enabled
  - name: kube-vip
    version: 0.6.1
    repository: https://kube-vip.github.io/helm-charts
  - name: harvester-load-balancer
    version: 1.6.1
    repository: https://charts.harvesterhci.io
  - name: whereabouts
    version: 0.1.1
    repository: file://dependency_charts/whereabouts
    condition: whereabouts.enabled
  - name: harvester-node-manager
    version: 1.6.1
    repository: https://charts.harvesterhci.io
  - name: snapshot-validation-webhook
    version: 0.2.0
    repository: file://dependency_charts/snapshot-validation-webhook
