name: Create Issue by Label

on:
  issues:
    types: [ labeled ]

jobs:
  create-backport-issue:
    name: Create Issue  
    if: contains(github.event.label.name, 'backport-needed/') || contains(github.event.label.name, 'require-ui/')
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github.event) }}
      GITHUB_OWNER: harvester
      GITHUB_MAIN_REPOSITORY: harvester
      GITHUB_PROJECT_NUMBER: "7"
      E2E_PIPELINE: "Review,Ready For Testing,Testing"
      GITHUB_REPOSITORY_TEST: tests
      GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install
        run: |
          pip install -r .github/workflows/bot/requirements.txt

      - name: Create Backport Issue
        if: contains(github.event.label.name, 'backport-needed/')
        run: |
          python .github/workflows/bot.py "$EVENT"
      
      - name: Create GUI Issue
        if: contains(github.event.label.name, 'require-ui/')
        run: |
          python .github/workflows/bot.py "$EVENT"