name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open for 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-stale: 60
          days-before-pr-stale: 45
          days-before-close: 5
          days-before-pr-close: 10
          stale-issue-label: 'status/stale'
          stale-pr-label: 'status/stale'
          exempt-all-assignees: true
          exempt-issue-labels: 'kind/enhancement,kind/feature'
          exempt-draft-pr: true
          exempt-all-milestones: true
